config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('machines.urls', 'machines'), namespace='machines')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machines/urls.py
"""Machines URLs."""

# Django
from django.urls import path

# Views
from machines import views

urlpatterns = [

    path(
        route='',
        view=views.MachineListView.as_view(),
        name='feed'
    ),

    path(
        route='machines/new/',
        view=views.CreateMachineView.as_view(),
        name='create'
    ),

    path(
        route='machines/<int:pk>/',
        view=views.MachineDetailView.as_view(),
        name='detail'
    ),

    path(
        route='machines/update/<int:pk>/',
        view=views.UpdateMachineView.as_view(),
        name='update'
    ),

    path(
        route='machines/rent/<int:pk>/',
        view=views.RentMachineView.as_view(),
        name='rent'
    )
]

tools/urls.py
"""Tools URLs."""

# Django
from django.urls import path

# Views
from tools import views

urlpatterns = [

    path(
        route='',
        view=views.ToolListView.as_view(),
        name='list'
    ),

    path(
        route='tools/new/',
        view=views.CreateToolView.as_view(),
        name='create'
    ),

    path(
        route='tools/<int:pk>/',
        view=views.ToolDetailView.as_view(),
        name='detail'
    ),

    path(
        route='tools/update/<int:pk>/',
        view=views.UpdateToolView.as_view(),
        name='update'
    ),

]

users/urls.py
"""User URLs"""

# Django
from django.urls import path

# View
from users import views

urlpatterns = [
	
	# Management
	path(
		route='login/',
		view=views.LoginView.as_view(),
		name='login'
	),
	path(
		route='logout/',
		view=views.LogoutView.as_view(),
		name='logout'
	),
	path(
		route='signup/',
		view=views.SignupView.as_view(),
		name='signup'
	),
	path(
		route='me/profile/',
		view=views.UpdateProfileView.as_view(),
		name='update'
	),

	path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    )
]

templates/base.html
{% load static %}
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
      <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
      <script src="https://use.fontawesome.com/c3a6cfe937.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/some.css' %}">
    {% block styles %}{% endblock %}
    {% block head_content %}{% endblock %}
  </head>
  <body>
  	<div class="area container-fluid">
  		{% block container %}
        	
        {% endblock %}
  	</div>
  	<nav class="main-menu">
            <ul>
                <li>
                    <a href="">
                        <i class="fa-2x"><img src="{{ request.user.profile.picture.url }}" class="rounded-circle" style="width: 30px; height: 30px; margin-left: 15px;"></i>
                        <span class="nav-text">
                            {{ request.user.username }}
                        </span>
                    </a>
                  
                </li>
                <li>
                    <a href="">
                        <i class="fa fa-tachometer fa-2x"></i>
                        <span class="nav-text">
                            Dashboard
                        </span>
                    </a>
                  
                </li>
                <li class="has-subnav">
                    <a href="{% url 'machines:feed' %}">
                        <i class="fa fa-truck fa-2x"></i>
                        <span class="nav-text">
                            Maquinas
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="{% url 'tools:list' %}">
                       <i class="fa fa-wrench fa-2x"></i>
                        <span class="nav-text">
                            Herramientas
                        </span>
                    </a>
                    
                </li>
                <li class="has-subnav">
                    <a href="#">
                       <i class="fa fa-users fa-2x"></i>
                        <span class="nav-text">
                            Empleados
                        </span>
                    </a>
                   
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-bar-chart-o fa-2x"></i>
                        <span class="nav-text">
                            Clientes
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-tasks fa-2x"></i>
                        <span class="nav-text">
                           Proyectos
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                       <i class="fa fa-table fa-2x"></i>
                        <span class="nav-text">
                            Tables
                        </span>
                    </a>
                </li>
                <li>
                   <a href="#">
                        <i class="fa fa-map-marker fa-2x"></i>
                        <span class="nav-text">
                            Maps
                        </span>
                    </a>
                </li>
                <li>
                    <a href="#">
                       <i class="fa fa-info fa-2x"></i>
                        <span class="nav-text">
                            Documentation
                        </span>
                    </a>
                </li>
            </ul>

            <ul class="logout">
                <li>
                   <a href="#">
                         <i class="fa fa-power-off fa-2x"></i>
                        <span class="nav-text">
                            Logout
                        </span>
                    </a>
                </li>  
            </ul>
        </nav>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
        {% block scripts %}{% endblock %}
  </body>
    </html>

templates/dashboard.html
{% extends "base.html" %}

{% block head_content %}
	<title>Dashboard | Concretos Montoya</title>
{% endblock %}

{% block container %}
	Dahsboard
{% endblock %}

templates/nav.html
{% load static %}
<!-- <nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "machines:feed" %}">
            <img src="{% static "img/concretos_logo.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else%}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "machines:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>
 -->

 

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>