config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('machines.urls', 'machines'), namespace='machines')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tools/urls.py
"""Tools URLs."""

# Django
from django.urls import path

# Views
from tools import views

urlpatterns = [

    path(
        route='',
        view=views.ToolListView.as_view(),
        name='list'
    ),

    path(
        route='tools/new/',
        view=views.CreateToolView.as_view(),
        name='create'
    ),

    path(
        route='tools/<int:pk>/',
        view=views.ToolDetailView.as_view(),
        name='detail'
    ),

    path(
        route='tools/update/<int:pk>/',
        view=views.UpdateToolView.as_view(),
        name='update'
    ),

]

tools/models.py
from django.db import models


class ToolType(models.Model):
	name = models.CharField(max_length=255, blank=False, null=False)

	def __str__(self):
		return self.name


class Tool(models.Model):
	name = models.CharField(max_length=255, blank=False, null=False)
	tool_type = models.ForeignKey(
		ToolType,
		on_delete=models.CASCADE
	)
	picture = models.ImageField(
		upload_to='tools/pictures',
		blank=True,
		null=True
	)

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

tools/forms/tools.py
"""Machine forms."""

# Django
from django import forms
from django.forms import (
	ModelForm,
	TextInput,
	EmailInput,
	Textarea,
	NumberInput,
	Select,
	FileInput,
    DateTimeInput
)
from datetimewidget.widgets import DateTimeWidget

# Models
from tools.models import Tool, ToolType


class ToolForm(ModelForm):
	"""Tool model form."""

	class Meta:
		"""Form settings."""
		
		model = Tool
		fields = (
			'name',
			'tool_type',
			'picture'
		)
		widgets = {
			'name': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Nombre'
            }),
            'tool_type': Select(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            }),
            'picture': FileInput(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            })
		}

tools/views.py
# Django
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic import (
	CreateView,
	UpdateView,
	DetailView,
	ListView
)

# Forms
from tools.forms import ToolForm

# Models
from tools.models import Tool, ToolType

# Python
from datetime import datetime


class ToolListView(LoginRequiredMixin, ListView):
	"""Return all tools."""

	template_name = 'list.html'
	model = Tool
	ordering = ('-created',)
	paginated_by = 30
	context_object_name = 'tools'


class ToolDetailView(LoginRequiredMixin, DetailView):

	template_name = 'tool_detail.html'
	queryset = Tool.objects.all()
	context_object_name = 'tool'

	def get_context_data(self, **kwargs):
		context = super(ToolDetailView, self).get_context_data(**kwargs)
		context['type'] = ToolType.objects.get(tool=kwargs['object'])
		return context


class CreateToolView(LoginRequiredMixin, CreateView):

	template_name = 'new_tool.html'
	form_class = ToolForm
	success_url = reverse_lazy('tools:list')


class UpdateToolView(LoginRequiredMixin, UpdateView):

	template_name = 'new_tool.html'
	model = Tool
	form_class = ToolForm

	def get_success_url(self):
		pk = self.kwargs['pk']
		return reverse_lazy('tools:detail', kwargs={'pk': pk})

tools/templates/list.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
<script src="https://use.fontawesome.com/c3a6cfe937.js"></script>
{% endblock %}

{% block head_content %}
    <title>Herramientas | Concretos Montoya</title>
{% endblock %}

{% block container %}
    
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="margin-top:20px;">
          <div class="card">
            <div class="card-header">
              Lista de Herramientas
              <a href="{% url 'tools:create' %}" class="btn btn-primary" style="float:right;">Agregar nueva herramienta</a>
            </div>
            <div class="card-body">
              <h5 class="card-title">Title</h5>
              <table id="tools_table" class="table table-stripped" cellspacing="0" width="100%">
                
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Tipo</th>
                    <th><center>Imagen</center></th>
                    <th>Fecha de creación</th>
                    <th>Acciones</th>
                  </tr>
                </thead>

                <tbody>
                  {% for tool in tools %}
                    <tr>
                      <td>{{ tool.name }}</td>
                      <td>{{ tool.tool_type }}</td>
                      <td>
                        <center>
                          <img src="{{ tool.picture.url }}" class="" width="30px" height="30px">
                        </center>
                      </td>
                      <td>{{ tool.created }}</td>
                      <td>
                        <a href=""><i class="far fa-edit"></i></a>
                        <a href=""><i class="far fa-trash-alt"></i></a>
                        <a href=""><i class="fas fa-bars"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>

              </table>

            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.5.0/velocity.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#tools_table').DataTable();
  } );
</script>
{% endblock %}

tools/templates/new_tool.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css">
{% endblock %}

{% block head_content %}
    <title>Agregar | Concretos Montoya</title>
{% endblock %}

{% block container %}
    
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="margin-top:20px;">
          <div class="card">
              <div class="card-body">
                <h5 class="card-title">Agregar una herramienta</h5>
                <form action="" method="post" enctype='multipart/form-data'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Nombre:</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label>Tipo de herramineta:</label>
                        {{ form.tool_type }}
                    </div>
                    <div class="form-group">
                        <label>Imagen:</label>
                        {{ form.picture }}
                    </div>
              </div>
              <div class="card-footer">
                <input class="btn btn-primary" type="submit" value="Guardar">
                <a href="{% url 'tools:list' %}" class="btn btn-danger" id="btn-cancel">Cancelar</a>
              </div>
            </form>
            </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.5.0/velocity.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#tools_table').DataTable();
  } );
</script>
{% endblock %}