config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('machines.urls', 'machines'), namespace='machines')),
    path('tools/', include(('tools.urls', 'tools'), namespace='tools')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

machines/urls.py
"""Machines URLs."""

# Django
from django.urls import path

# Views
from machines import views

urlpatterns = [

    path(
        route='',
        view=views.MachineListView.as_view(),
        name='feed'
    ),

    path(
        route='machines/new/',
        view=views.CreateMachineView.as_view(),
        name='create'
    ),

    path(
        route='machines/<int:pk>/',
        view=views.MachineDetailView.as_view(),
        name='detail'
    ),

    path(
        route='machines/update/<int:pk>/',
        view=views.UpdateMachineView.as_view(),
        name='update'
    ),

    path(
        route='machines/rent/<int:pk>/',
        view=views.RentMachineView.as_view(),
        name='rent'
    )
]

tools/urls.py
"""Tools URLs."""

# Django
from django.urls import path

# Views
from tools import views

urlpatterns = [

    path(
        route='',
        view=views.ToolListView.as_view(),
        name='list'
    ),

    path(
        route='tools/new/',
        view=views.CreateToolView.as_view(),
        name='create'
    ),

    path(
        route='tools/<int:pk>/',
        view=views.ToolDetailView.as_view(),
        name='detail'
    ),

    path(
        route='tools/update/<int:pk>/',
        view=views.UpdateToolView.as_view(),
        name='update'
    ),

]

machines/models/machines.py
	# Django
from django.db import models


class Machine(models.Model):

	name = models.CharField(max_length=70, blank=False, null=False)
	serial_number = models.CharField(max_length=255, blank=True, null=True)
	model = models.CharField(max_length=255, blank=True, null=True)
	description = models.TextField()
	price = models.FloatField()
	machine_type = models.ForeignKey('machines.Type', on_delete=models.CASCADE)
	is_available = models.BooleanField(default=True)
	rent_price = models.FloatField(default=0)

	photo = models.ImageField(
		upload_to='machines/pictures',
		blank=True,
		null=True
	)

	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

machines/models/machines_rent.py
from django.db import models


class Rent(models.Model):

	client = models.CharField(
		max_length=255,
		blank=False,
		null=False
	)
	
	machine = models.ForeignKey(
		'machines.Machine',
		on_delete=models.CASCADE
	)

	rent_from = models.DateTimeField(
		auto_now=False,
		auto_now_add=False,
		blank=False,
		null=False
	)

	rent_to = models.DateTimeField(
		auto_now=False,
		auto_now_add=False,
		blank=False,
		null=False
	)

	notes = models.TextField()

	def __str__(self):
		return self.client

machines/models/types.py
from django.db import models


class Type(models.Model):

	name = models.CharField(max_length=50, blank=False, null=False)
	description = models.CharField(max_length=50, blank=False, null=False)

	def __str__(self):
		return self.name

machines/forms.py
"""Machine forms."""

# Django
from django import forms
from django.forms import (
	ModelForm,
	TextInput,
	EmailInput,
	Textarea,
	NumberInput,
	Select,
	FileInput
)

# Models
from machines.models import Machine


class MachineForm(ModelForm):
	"""Machine model form."""

	class Meta:
		"""Form settings."""
		
		model = Machine
		fields = (
			'name',
			'serial_number',
			'model',
			'description',
			'price',
			'machine_type',
			'photo'
		)
		widgets = {
			'name': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Nombre'
            }),
            'serial_number': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Número de serie'
            }),
            'model': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Modelo'
            }),
            'description': Textarea(attrs={
                'class': "form-control",
                'rows': '5',
                'placeholder': 'Descripción'
            }),
            'price': NumberInput(attrs={
                'class': "form-control",
                'placeholder': 'Precio'
            }),
            'machine_type': Select(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            }),
            'photo': FileInput(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            })
            # 'serial_number': EmailInput(attrs={
            #     'class': "form-control", 
            #     'style': 'max-width: 300px;',
            #     'placeholder': 'Email'
            # })
		}

machines/forms/machines.py
"""Machine forms."""

# Django
from django import forms
from django.forms import (
	ModelForm,
	TextInput,
	EmailInput,
	Textarea,
	NumberInput,
	Select,
	FileInput,
    DateTimeInput
)
from datetimewidget.widgets import DateTimeWidget

# Models
from machines.models import Machine, Rent


class MachineForm(ModelForm):
	"""Machine model form."""

	class Meta:
		"""Form settings."""
		
		model = Machine
		fields = (
			'name',
			'serial_number',
			'model',
			'description',
			'price',
			'machine_type',
			'photo'
		)
		widgets = {
			'name': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Nombre'
            }),
            'serial_number': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Número de serie'
            }),
            'model': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Modelo'
            }),
            'description': Textarea(attrs={
                'class': "form-control",
                'rows': '5',
                'placeholder': 'Descripción'
            }),
            'price': NumberInput(attrs={
                'class': "form-control",
                'placeholder': 'Precio'
            }),
            'machine_type': Select(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            }),
            'photo': FileInput(attrs={
                'class': "form-control",
                'placeholder': 'Tipo'
            })
            # 'serial_number': EmailInput(attrs={
            #     'class': "form-control", 
            #     'style': 'max-width: 300px;',
            #     'placeholder': 'Email'
            # })
		}

machines/forms/rents.py
"""Machine forms."""

# Django
from django import forms
from django.forms import (
	ModelForm,
	TextInput,
	EmailInput,
	Textarea,
	NumberInput,
	Select,
	FileInput,
    DateTimeInput
)
from datetimewidget.widgets import DateTimeWidget

# Models
from machines.models import Machine, Rent


class RentForm(ModelForm):

    def __init__(self, machine_pk, *args, **kwargs):
        super(RentForm, self).__init__(*args, **kwargs)
        print(machine_pk)
        self.fields['machine'].widget = forms.TextInput(attrs={
            'class': "form-control hidden-input",
            'placeholder': 'Cliente',
            'value': machine_pk
        })

    class Meta:

        model = Rent
        fields = (
            'client',
            'machine',
            'rent_from',
            'rent_to',
            'notes'
        )
        widgets = {
            # 'client': Select(attrs={
            #     'class': "form-control",
            #     'placeholder': 'Cliente'
            # }),
            'client': TextInput(attrs={
                'class': "form-control",
                'placeholder': 'Cliente'
            }),
            'machine': TextInput(),
            'rent_from': DateTimeInput(attrs={
                'id': 'datetimepicker1',
                'class': "form-control datetimepicker-input",
                'placeholder': 'Escoje la fecha de inicio',
                'data-target': '#datetimepicker1'
            }),
            'rent_to': DateTimeInput(attrs={
                'id': 'datetimepicker2',
                'class': "form-control datetimepicker-input",
                'placeholder': 'Escoje la fecha de termino',
                'data-target': '#datetimepicker2'
            }),
            'notes': Textarea(attrs={
                'class': "form-control",
                'rows': '5',
                'placeholder': 'Notas'
            }),
        }

    # def save(self, commit=True):
    #     print(self.cleaned_data['machine'])
    #     machine = Machine.objects.get(pk=self.cleaned_data['machine'])
    #     self.cleaned_data['machine'] = machine
    #     return super(RentForm, self).save(commit)

    # def clean_machine(self):
    #     machineid = self.cleaned_data['machine']
    #     print(self.cleaned_data)
    #     print(machineid.pk)
    #     try:
    #         machine = Machine.objects.get(pk=machineid.pk)
    #     except Machine.DoesNotExists:
    #         raise ValidationError('There is not machine with pk {}'.format(machine))
    #     return machine.pk

machines/views.py
# Django
from django.urls import reverse_lazy
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.views.generic import (
	CreateView,
	UpdateView,
	DetailView,
	ListView
)

# Forms
from machines.forms import MachineForm, RentForm

# Models
from machines.models import Machine, Rent

# Python
from datetime import datetime


class MachineListView(LoginRequiredMixin, ListView):
	"""Return all machines."""

	template_name = 'feed.html'
	model = Machine
	ordering = ('-created',)
	paginated_by = 30
	context_object_name = 'machines'


class MachineDetailView(LoginRequiredMixin, DetailView):

	template_name = 'detail.html'
	queryset = Machine.objects.all()
	context_object_name = 'machine'

	def get_context_data(self, **kwargs):
		print(kwargs['object'])
		context = super(MachineDetailView, self).get_context_data(**kwargs)
		context['rent'] = Rent.objects.filter(machine=kwargs['object'])
		return context


class CreateMachineView(LoginRequiredMixin, CreateView):

	template_name = 'new.html'
	form_class = MachineForm
	success_url = reverse_lazy('machines:feed')


class UpdateMachineView(LoginRequiredMixin, UpdateView):

	template_name = 'new.html'
	model = Machine
	form_class = MachineForm

	def get_success_url(self):
		pk = self.kwargs['pk']
		return reverse_lazy('machines:detail', kwargs={'pk': pk})


class RentMachineView(LoginRequiredMixin, FormView):

	template_name = 'rent.html'
	model = Rent

	def post(self, request, *args, **kwargs):
		
		client = request.POST['client']
		machine = Machine.objects.get(pk=int(request.POST['machine']))
		rent_from = request.POST['rent_from']
		rent_to = request.POST['rent_to']
		notes = request.POST['notes']

		# Format datetime
		rent_from = datetime.strptime(rent_from, '%Y/%m/%d %H:%M')
		rent_to = datetime.strptime(rent_to, '%Y/%m/%d %H:%M')

		try:
			Rent.objects.create(
				client=client,
				machine=machine,
				rent_from=rent_from,
				rent_to=rent_to,
				notes=notes
			)
		except Exception as e:
			print(e)

		machine.is_available = False
		machine.save()

		return redirect('machines:detail', pk=machine.pk)

	def get(self, request, pk):
		form_class = RentForm(machine_pk=pk)
		return render(request, self.template_name, {'form': form_class})


	def form_valid(self, form):
		print(form.cleaned_data)
		# print(form.instance.machine)
		# form.instance.machine = self.machine
		return super(RentMachineView, self).form_valid(form)

	def get_success_url(self):
		pk = self.kwargs['pk']
		return reverse_lazy('machines:detail', kwargs={'pk': pk})

machines/templates/detail.html
{% extends "base.html" %}

{% load static %}

{% block head_content %}
    <title>Detalles | Concretos Montoya</title>
{% endblock%}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'schedule/core/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'schedule/daygrid/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'schedule/timegrid/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'schedule/list/main.css' %}">
{% endblock %}

{% block container %}

    <div class="container">
      <div class="row">
        <div class="col-md-5" style="margin-top: 20px;">
              <div class="card">
                  <div class="card-body">
                  	<div class="row">
                  		<div class="col-md-4">
                  			{% if machine.photo %}
                  				<img src="{{ machine.photo.url }}" class="rounded-circle" style="width: 180px; height: 180px;" />
                  			{% else %}
                  				<img src="{% static 'img/default_machine.jpg' %}" class="rounded-circle" />
                  			{% endif %}
                  		</div>
                  		<div class="col-md-8">
                  			<h5 class="card-title">{{ machine.name }}</h5>
		                    <p class="card-text" style="height: 60px;">
		                    	{{ machine.description }}
		                    </p>
                  		</div>
                  	</div>
                    
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                      <strong>Número de serie:</strong> {{ machine.serial_number }}
                    </li>
                    <li class="list-group-item">
                      <strong>Modelo:</strong> {{ machine.model }}
                    </li>
                    <li class="list-group-item">
                      <strong>Price de compra:</strong> {{ machine.price }}
                    </li>
                    <li class="list-group-item">
                      <strong>Tipo:</strong> {{ machine.machine_type }}
                    </li>
                    {% if machine.is_available %}
                      <li class="list-group-item">
                        <strong>Estatus:</strong> 
                        <span class="bg-success" style="border:none; color: white; padding: 2px; border-radius: 5px; "><b>Disponible</b></span>
                      </li>
                    {% else %}
                      <li class="list-group-item">
                        <strong>Estatus:</strong> 
                        <span class="bg-warning" style="border:none; color: white; padding: 2px; border-radius: 5px; "><b>En renta</b></span>
                      </li>
                    {% endif %}
                    <li class="list-group-item">
                      <strong>Precio de renta:</strong> {{ machine.rent_price }}
                    </li>
                  </ul>
              </div>
            </div>

            <div class="col-md-5" style="margin-top: 20px;">
              <div id="calendar" style="background-color: white;"></div>
            </div>

            <div class="col-md-2" style="margin-top: 20px;">
              <div class="btn-group-vertical">
                <a href="{% url 'machines:feed' %}" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Regresar">
                  <i class="fa fa-undo fa-2x"></i>
                </a>
                <a href="{% url 'machines:update' machine.pk %}" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Editar">
                  <i class="fa fa-edit fa-2x"></i>
                </a>
                <a href="{% url 'machines:rent' machine.pk %}" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="top" title="Rentar">
                  <i class="fa fa-shopping-cart fa-2x"></i>
                </a>
              </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
<script type="text/javascript" src="{% static 'schedule/core/main.js' %}"></script>
<script type="text/javascript" src="{% static 'schedule/interaction/main.js' %}"></script>
<script type="text/javascript" src="{% static 'schedule/daygrid/main.js' %}"></script>
<script type="text/javascript" src="{% static 'schedule/timegrid/main.js' %}"></script>
<script type="text/javascript" src="{% static 'schedule/list/main.js' %}"></script>

<script type="text/javascript">
  var calendarEl = document.getElementById('calendar');

  var calendar = new FullCalendar.Calendar(calendarEl, {
    locale: 'es',
    plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
    height: 'parent',
    header: {
      left: 'prev,next today',
      center: 'title',
      // right: 'dayGridMonth,timeGridWeek,timeGridDay,listWeek'
      right: false 
    },
    defaultView: 'dayGridMonth',
    //defaultDate: '{% now "Y-m-d" %}',
    navLinks: true, // can click day/week names to navigate views
    editable: false,
    eventLimit: true, // allow "more" link when too many events
    events: [
      {% for r in rent %}
        {
          title: '{{ r.client }}',
          start: '{{ r.rent_from|date:"Y-m-d H:m" }}',
          end: '{{ r.rent_to|date:"Y-m-d H:m" }}',
          color: '#33C3FF'
        },
      {% endfor %}
    ]

  });

  calendar.render();
</script>
{% endblock %}

machines/templates/feed.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
{% endblock %}

{% block head_content %}
    <title>Machines | Concretos Montoya</title>
{% endblock %}

{% block container %}
    <div style="margin-left: 3.3%;">

      <!-- search nav -->
      <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
          <form class="d-flex">
            <input class="form-control me-2" id="machine_search" type="search" placeholder="Buscar" aria-label="Search">
            <select class="form-control me-2" id="machine_status_search">
              <option>-----------</option>
              <option>En renta</option>
              <option>Disponible</option>
            </select>
            <button class="btn btn-outline-primary" type="submit">Search</button>
          </form>
          <a class="navbar-brand">Máquinas</a>
        </div>
      </nav>
      <!-- end search nav -->

      <div class="row machine_list" style="margin-top: 5px;">
        {% for machine in machines %}
            {% if machine.is_available %}
              <div class="col-md-3 available" id="{{machine.name}}">
            {% else %}
              <div class="col-md-3 not-available" id="{{machine.name}}">
            {% endif %}
                <div class="card" >
                    {% if machine.photo %}
                      <img
                        src="{{ machine.photo.url }}"
                        class="card-img-top"
                        alt="..."
                        style="height: 180px;"
                      />
                    {% else %}
                      <img
                        src="{% static 'img/default_machine.jpg' %}"
                        class="card-img-top"
                        alt="..."
                        style="height: 180px;"
                      />
                    {% endif %}
                    <div class="card-body">
                      <div class="row">
                        <div class="col">
                          <h5 class="card-title">{{ machine.name }}</h5>
                        </div>
                        <div class="col">
                          <a href="{% url 'machines:detail' machine.pk %}" style="float: right;" data-bs-toggle="tooltip" data-bs-placement="top" title="Ver detalles">
                            <i class="fa fa-bars"></i>
                          </a>
                        </div>
                      </div>
                      <div class="row">
                        <p class="card-text" style="height: 60px;">
                          {{ machine.description }}
                        </p>
                      </div>
                    </div>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item">
                        <strong>Número de serie:</strong> {{ machine.serial_number }}
                      </li>
                      <li class="list-group-item">
                        <strong>Modelo:</strong> {{ machine.model }}
                      </li>
                      <li class="list-group-item">
                        <strong>Precio de compra:</strong> {{ machine.price }}
                      </li>
                      <li class="list-group-item">
                        <strong>Tipo:</strong> {{ machine.machine_type }}
                      </li>
                      {% if machine.is_available %}
                        <li class="list-group-item">
                          <strong>Estatus:</strong> 
                          <span class="bg-success" style="border:none; color: white; padding: 2px; border-radius: 5px; "><b>Disponible</b></span>
                        </li>
                      {% else %}
                        <li class="list-group-item">
                          <strong>Estatus:</strong> 
                          <span class="bg-warning" style="border:none; color: white; padding: 2px; border-radius: 5px; "><b>En renta</b></span>
                        </li>
                      {% endif %}
                      <li class="list-group-item">
                        <strong>Precio de renta:</strong> {{ machine.rent_price }}
                      </li>
                    </ul>
                    <!-- <div class="card-footer"> -->
                      <!-- <button class="btn btn-primary">Editar</button> -->
                      <!-- <a href="{% url 'machines:detail' machine.pk %}" class="btn btn-primary" style="float: right;">
                        <i class="fa fa-bars"></i>
                      </a> -->
                    <!-- </div> -->
                </div>
            </div>
        {% endfor %}
      </div>
    </div>


    <div class="zoom">
      <a class="zoom-fab zoom-btn-large" id="zoomBtn"><i class="fa fa-bars"></i></a>
      <ul class="zoom-menu">
        <li><a href="{% url 'machines:create' %}" class="zoom-fab zoom-btn-sm zoom-btn-person scale-transition scale-out"><i class="fa fa-plus"></i></a></li>
        <li><a class="zoom-fab zoom-btn-sm zoom-btn-report scale-transition scale-out"><i class="fa fa-edit"></i></a></li>
        <li><a class="zoom-fab zoom-btn-sm zoom-btn-doc scale-transition scale-out"><i class="fa fa-calendar"></i></a></li>
        <li><a class="zoom-fab zoom-btn-sm zoom-btn-tangram scale-transition scale-out"><i class="fa fa-calendar"></i></a></li>
        <li><a class="zoom-fab zoom-btn-sm zoom-btn-feedback scale-transition scale-out"><i class="fa fa-bell"></i></a></li>
      </ul>
      <div class="zoom-card scale-transition scale-out">
        <ul class="zoom-card-content">
        <li>Content</li>
        <li>Content</li>
        <li>Content</li>
        <li>Content</li>
        <li>Content</li>
        </ul>
      </div>
    </div>

{% endblock %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/velocity/1.5.0/velocity.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}

machines/templates/new.html
{% extends "base.html" %}

{% load static %}

{% block container %}
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6 justify-content-center" style="margin-top: 20px;">

            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Agregar una máquina</h5>
                <form action="" method="post" enctype='multipart/form-data'>
                        {% csrf_token %}
                    <div class="form-group">
                        <label>Nombre:</label>
                        {{ form.name }}
                    </div>
                    <div class="form-group">
                        <label>Número de serie:</label>
                        {{ form.serial_number }}
                    </div>
                    <div class="form-group">
                        <label>Modelo:</label>
                        {{ form.model }}
                    </div>
                    <div class="form-group">
                        <label>Descripción:</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group">
                        <label>Precio:</label>
                        {{ form.price }}
                    </div>
                    <div class="form-group">
                        <label>Tipo:</label>
                        {{ form.machine_type }}
                    </div>
                    <div class="form-group">
                        <label>Foto:</label>
                        {{ form.photo }}
                    </div>
              </div>
              <div class="card-footer">
                <input class="btn btn-primary" type="submit" value="Guardar">
                <a href="{% url 'machines:feed' %}" class="btn btn-danger" id="btn-cancel">Cancelar</a>
              </div>
            </form>
            </div>
            
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

machines/templates/rent.html
{% extends "base.html" %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.min.css' %}">
    <style type="text/css">
        .hidden-input{
            display: none;
        }
    </style>
{% endblock %}

{% block container %}
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6 justify-content-center" style="margin-top: 20px;">

            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Rentar máquina</h5>
                <form action="" method="post">
                        {% csrf_token %}
                        {{ form.errors }}
                    <div class="form-group">
                        <label>Cliente:</label>
                        {{ form.client }}
                    </div>
                    <div class="form-group">
                        <!-- <label>Maquina:</label> -->
                        {{ form.machine }}
                    </div>
                    <div class="form-group">
                        <label>Rentar desde:</label>
                        {{ form.rent_from }}
                        <!-- <input type="datetime-local" name="rent_from" id="id_rent_from" class="form-control"> -->
                    </div>
                    <div class="form-group">
                        <label>Rentar hasta:</label>
                         <!-- <input type="datetime-local" name="rent_to" id="id_rent_to" class="form-control"> -->
                         {{ form.rent_to }}
                    </div>
                    <div class="form-group">
                        <label>Notas:</label>
                        {{ form.notes }}
                        <!-- <textarea name="notes" id="id_notes" class="form-control"> -->
                        	
                        <!-- </textarea> -->
                    </div>
              </div>
              <div class="card-footer">
                <input class="btn btn-primary" type="submit" value="Rentar">
                <a href="{% url 'machines:feed' %}" class="btn btn-danger">Cancelar</a>
              </div>
            </form>
            </div>
            
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.datetimepicker.full.js' %}"></script>
	<script>
      $(function () {
        $('#datetimepicker1').datetimepicker({});
        $('#datetimepicker2').datetimepicker({});
      });
    </script>
{% endblock %}